/**
 * Textos en español para el prompt cuando la UI está en ES (valueEs en cada opción).
 * Debe cargarse justo después de data.js.
 */
(function () {
  const D = window.GenFotoPrompts_DATA;
  if (!D) return;

  function byId(arr, map) {
    arr.forEach((o) => {
      if (o.id && Object.prototype.hasOwnProperty.call(map, o.id)) {
        o.valueEs = map[o.id];
      }
    });
  }

  function applyOrder(arr, list) {
    arr.forEach((o, i) => {
      if (list[i] !== undefined) o.valueEs = list[i];
    });
  }

  byId(D.atmosphere, {
    atmoFog:
      'niebla baja arrastrándose por el suelo, concentrada a la altura de los pies, fina y translúcida',
    atmoPetals: 'pétalos de flor delicados flotando suavemente en el aire alrededor del sujeto',
    atmoSnow: 'copos de nieve cayendo suavemente alrededor del sujeto, escarcha en superficies cercanas',
    atmoRain: 'lluvia ligera con gotas visibles a la luz, superficies mojadas reflectantes, surcos de lluvia',
    atmoFireflies: 'luciérnagas mágicas y partículas luminosas flotando en el aire',
    atmoDust: 'partículas de polvo visibles bailando en los haces de luz',
    atmoLeaves: 'hojas otoñales cayendo y arremolinándose con una brisa ligera',
    atmoSteam: 'vapor y bruma atmosférica ascendiendo desde el suelo',
    atmoSparks: 'chispas doradas mágicas y brasas flotando hacia arriba',
    atmoBokeh: 'orbes de luz bokeh hermosos en el fondo',
    atmoStorm: 'nubes de tormenta dramáticas, relámpagos lejanos, atmósfera cargada',
    atmoRainbow: 'bruma arcoíris suave y refracción de luz en el aire',
    atmoHaze: 'bruma atmosférica fina suavizando edificios lejanos',
    atmoSunbeams: 'rayos de sol atravesando nubes y árboles',
    atmoUnderwater: 'cáusticas de luz subacuática danzando sobre las superficies',
    atmoHeat: 'calor sutil distorsionando el aire con temblores',
    atmoPollen: 'partículas de polen brillantes flotando suavemente',
    atmoSmoke: 'humo suave flotando en el fondo',
    atmoEmbers: 'pequeñas partículas de ceniza flotando en el aire',
    atmoSnowstorm: 'ventisca ligera con nieve arremolinada',
    atmoBreeze: 'brisa suave moviendo tela y cabello',
    atmoGlow: 'brillo ambiental suave alrededor del sujeto',
    atmoMist: 'niebla densa llenando la escena',
    atmoLens: 'destellos y reflejos sutiles en el aire',
    atmoAurora: 'tenues franjas de aurora en el cielo',
    atmoBubbles: 'burbujas de jabón flotando y refractando la luz',
    atmoConfetti: 'confeti de colores cayendo en cámara lenta',
    atmoTears: 'gotas con forma de lágrima flotando en ingravidez'
  });

  (function patchLightingKey() {
    const map = {
      'warm golden hour sunlight from the right': 'luz dorada de hora dorada desde la derecha',
      'cold blue moonlight from above': 'luz de luna azul fría desde arriba',
      'soft natural window light from the left': 'luz natural suave de ventana desde la izquierda',
      'dramatic side lighting from the left creating deep shadows':
        'luz lateral dramática desde la izquierda con sombras profundas',
      'bright overhead tropical sunlight': 'luz solar tropical brillante cenital',
      'soft overcast diffused light from cloudy sky': 'luz difusa nublada suave desde el cielo',
      'neon colored light from signs and screens': 'luz de neón de carteles y pantallas',
      'warm candlelight and firelight': 'luz cálida de velas y fuego',
      'Rembrandt lighting with key light at 45 degrees creating triangle on cheek':
        'iluminación Rembrandt con luz principal a 45° formando triángulo en la mejilla',
      'butterfly lighting from above creating shadow under nose':
        'iluminación mariposa desde arriba con sombra bajo la nariz',
      'large softbox light, even and soft': 'luz de softbox grande, uniforme y suave',
      'studio strobe flash lighting': 'flash de estudio tipo stroboscópico',
      'red emergency light casting dramatic tones': 'luz de emergencia roja con tonos dramáticos',
      'cool blue fill light from the right': 'luz de relleno azul fría desde la derecha',
      'warm tungsten light indoor': 'luz cálida de tungsteno en interior',
      'direct flashlight beam as key light': 'haz de linterna directa como luz principal',
      'car headlights as the main light source': 'faros de coche como fuente principal de luz',
      'streetlamp light casting long shadows': 'luz de farola proyectando sombras largas',
      'fireplace light flickering warmly': 'luz de chimenea parpadeando cálidamente',
      'theater spotlight from above': 'foco teatral cenital',
      'colorful dance floor spotlights': 'focos de pista de baile de colores',
      'hard top-down light creating strong shadows': 'luz cenital dura con sombras fuertes',
      'window blinds light stripes across subject': 'franjas de luz de persianas cruzando al sujeto',
      'icy blue light giving cold mood': 'luz helada azulada con ambiente frío',
      'soft ambient light wrapping the subject': 'luz ambiental suave envolviendo al sujeto',
      'light refracting through crystal, rainbow caustics': 'luz refractándose a través de cristal, cáusticas de arcoíris'
    };
    D.lightingKey.forEach((o) => {
      if (map[o.value]) o.valueEs = map[o.value];
    });
  })();

  byId(D.lightingTech, {
    lightRim: 'luz de contorno cálida desde detrás del sujeto',
    lightVol: 'rayos de luz volumétricos suaves visibles en la atmósfera',
    lightHighKey: 'iluminación high-key con pocas sombras, brillante y aireada',
    lightLowKey: 'iluminación low-key con sombras profundas y luces selectivas',
    lightFlare: 'destello de lente suave desde la fuente de luz',
    lightChiaroscuro: 'claroscuro con fuerte contraste entre luz y sombra',
    lightDappled: 'patrón de luz filtrada entre hojas o ramas',
    lightHard: 'luz dura con sombras nítidas',
    lightSoft: 'luz suave con transiciones graduales',
    lightSplit: 'iluminación split dividiendo rostro en luz y sombra',
    lightShort: 'iluminación short resaltando contornos faciales',
    lightBroad: 'iluminación broad llenando el rostro de forma uniforme',
    lightGels: 'iluminación con geles de color para tonos estilizados',
    lightBounce: 'luz rebotada rellenando sombras suavemente',
    lightFill: 'luz de relleno para reducir sombras duras',
    lightPractical: 'luces prácticas visibles en la escena',
    lightSilhouette: 'silueta con solo contraluz',
    lightEdge: 'luz de borde delineando al sujeto',
    lightClamshell: 'iluminación clam con luz superior e inferior',
    lightFlat: 'luz plana con poco contraste',
    lightMotivated: 'iluminación motivada según fuentes de la escena',
    lightAmbient: 'luz ambiental dominando la escena',
    lightBack: 'contraluz fuerte para separar al sujeto',
    lightNeon: 'doble iluminación de neón con colores contrastados',
    lightGodrays: 'rayos crepusculares visibles atravesando la atmósfera',
    lightFairy: 'luces puntuales diminutas de hada esparcidas'
  });

  (function patchStyles() {
    const map = {
      'hyperrealistic photography': 'fotografía hiperrealista',
      'cinematic film still': 'fotograma de cine',
      'editorial fashion photography': 'fotografía editorial de moda',
      'fine art portrait photography': 'fotografía de retrato de arte',
      'documentary photography': 'fotografía documental',
      'digital oil painting, highly detailed brushstrokes': 'pintura digital al óleo, pinceladas muy detalladas',
      'watercolor illustration with soft edges': 'ilustración en acuarela con bordes suaves',
      '3D render, octane render, highly detailed': 'render 3D, octane render, muy detallado',
      'anime style, detailed anime illustration': 'estilo anime, ilustración anime detallada',
      'dark fantasy art, highly detailed digital painting': 'arte fantástico oscuro, pintura digital muy detallada',
      'concept art, matte painting style': 'concept art, estilo matte painting',
      'vintage film photograph, Kodak Portra 400 film grain':
        'fotografía vintage en película, grano Kodak Portra 400',
      'low poly 3D style, clean geometry': 'estilo 3D low poly, geometría limpia',
      'minimalist composition, clean shapes': 'composición minimalista, formas limpias',
      'ink illustration with bold lines': 'ilustración de tinta con trazos marcados',
      'flat design, vector style': 'diseño plano, estilo vectorial',
      'isometric illustration, clean perspective': 'ilustración isométrica con perspectiva limpia',
      'mixed media collage, layered textures': 'collage multimedia con texturas superpuestas',
      'film grain, analog texture': 'grano de película, textura analógica',
      'noir photography, high contrast shadows': 'fotografía noir con sombras de alto contraste',
      'surreal dreamlike visual style': 'estilo visual surrealista onírico',
      'baroque painting style, ornate details': 'estilo barroco, detalles ornamentados',
      'magical realism with subtle fantasy elements': 'realismo mágico con toques fantásticos sutiles',
      'HDR realistic photography, crisp detail': 'fotografía HDR realista, detalle nítido',
      'pastel illustration with soft gradients': 'ilustración pastel con degradados suaves',
      'tenebrism, extreme contrasts, theatrical darkness': 'tenebrismo, contrastes extremos, oscuridad teatral'
    };
    D.styles.forEach((o) => {
      if (map[o.value]) o.valueEs = map[o.value];
    });
  })();

  applyOrder(D.cameras, [
    'fotografía con Canon EOS R5',
    'fotografía con Sony A7R IV',
    'fotografía con Nikon Z9',
    'fotografía con Hasselblad X2D',
    'fotografía con Fujifilm GFX 100S',
    'fotografía con Leica M11',
    'fotografía con Canon 5D Mark IV',
    'fotografía con Sony A1',
    'fotografía con Sony FX3',
    'fotografía con Panasonic S1H',
    'fotografía con RED Komodo',
    'fotografía con Blackmagic Pocket 6K',
    'fotografía con Arri Alexa Mini',
    'fotografía con Canon C70',
    'fotografía con Nikon D850',
    'fotografía con Fujifilm X-T5',
    'fotografía con Olympus OM-1',
    'fotografía con Pentax K-1',
    'fotografía con Sony A7S III',
    'fotografía con Canon R6',
    'fotografía con Nikon Z6 II',
    'fotografía con Fujifilm X100V',
    'fotografía con Ricoh GR III',
    'fotografía con Phase One XF',
    ''
  ]);

  applyOrder(D.lenses, [
    'objetivo 85 mm f/1,4, poca profundidad de campo',
    'objetivo 50 mm f/1,2, perspectiva natural',
    'objetivo 35 mm f/1,4, perspectiva ligeramente angular',
    'objetivo 135 mm f/2, fondo comprimido, bokeh hermoso',
    'objetivo gran angular 24 mm f/2,8, campo amplio',
    'objetivo macro 100 mm, detalle extremo',
    'objetivo ultra gran angular 16 mm f/2,8, perspectiva dramática',
    'objetivo 28 mm f/1,8, campo inmersivo',
    'objetivo 40 mm f/2, estética callejera natural',
    'objetivo 70-200 mm f/2,8, fondo comprimido',
    'objetivo zoom 24-70 mm f/2,8, encuadre versátil',
    'objetivo 200 mm f/2,8 teleobjetivo',
    'objetivo 14 mm f/2,8 ultra gran angular extremo',
    'objetivo 55 mm f/1,8, nítido y definido',
    'objetivo macro 90 mm f/2,8',
    'objetivo 105 mm f/1,4, bokeh cremoso',
    'objetivo 35 mm f/2, sensación documental',
    'objetivo 18 mm f/1,8, mirada callejera dinámica',
    'objetivo retrato 65 mm f/2,8',
    'objetivo 135 mm f/1,8, compresión marcada',
    'objetivo 24 mm f/1,4, mirada cinematográfica amplia',
    'objetivo 70 mm f/2,8, perspectiva favorecedora',
    'objetivo 300 mm f/4, teleobjetivo extremo',
    'objetivo 45 mm f/1,8, visión natural limpia',
    ''
  ]);

  byId(D.quality, {
    qual8k: 'resolución 8K',
    qualUltra: 'ultradetallado',
    qualRaw: 'foto RAW',
    qualSharp: 'enfoque nítido en el sujeto',
    qualCinematic: 'gradación de color cinematográfica',
    qualSkin: 'textura de piel natural, poros detallados',
    qualHdr: 'alto rango dinámico',
    qualClean: 'imagen limpia, sin ruido',
    qualTexture: 'textura de superficie rica',
    qualDoF: 'poca profundidad de campo',
    qualBokeh: 'fondo con bokeh cremoso',
    qualContrast: 'iluminación de alto contraste',
    qualSoft: 'tonos de contraste suave',
    qualColor: 'reproducción de color precisa',
    qualGI: 'iluminación global',
    qualSSS: 'dispersión subsuperficial',
    qualAO: 'oclusión ambiental',
    qualSharp2: 'microdetalles y textura fina',
    qualFilm: 'grano de película sutil',
    qualCrisp: 'bordes nítidos y claridad',
    qualClean2: 'sin artefactos ni fallos',
    qualStudio: 'claridad y luz de estudio',
    qualPro: 'imagen de nivel profesional',
    qualVignette: 'viñeta sutil',
    qualTilt: 'efecto tilt-shift de enfoque'
  });

  applyOrder(D.palettes, [
    'tonos fríos desaturados, azules profundos y verdes azulados, acentos naranjas cálidos selectivos',
    'tonos pastel suaves, rosa melocotón, melocotón, verdes frescos, acentos dorados cálidos, lavanda',
    'blancos fríos, azules helados, ámbar cálido, verdes bosque profundos, reflejos plateados',
    'turquesa y aguamarina vivos, arena dorada cálida, verdes exuberantes, acentos coral',
    'negros profundos, cian eléctrico, magenta intenso, neón púrpura, grises acero fríos',
    'naranja tostado, carmesí profundo, oro cálido, marrón chocolate, verde oliva',
    'tonos dorados cálidos, ámbar miel, crema suave, toques burdeos',
    'paleta monocromática azul, desde azul marino hasta cielo',
    'blanco y negro con acentos de color selectivos',
    'tonos tierra apagados, verde salvia, terracota, beige cálido, rosa polvo',
    'gradación cinematográfica teal y naranja, contraste complementario',
    'lavanda soñadora, púrpura suave, azul brumoso, blanco etéreo',
    'paleta atardecer, naranjas y rosas cálidos',
    'paleta mínima fría, azules helados y grises suaves',
    'grises suaves, tonos apagados, contraste mínimo',
    'verde esmeralda, acentos dorados, negros profundos',
    'beige arena, naranja arcilla, neutros cálidos',
    'rojos monocromáticos, variaciones carmesí profundo',
    'paleta vaporwave, brillo cian y magenta',
    'azules oceánicos, degradados turquesa, acentos espuma de mar',
    'tonos sepia, calidez vintage',
    'terracota y paleta tierra cálida',
    'acentos amarillos, energía luminosa',
    'púrpura real, violeta profundo, brillos elegantes',
    'verdes bosque profundos, musgo, marrones oscuros',
    'pasteles caramelo, rosa chicle, menta, azul bebé'
  ]);

  byId(D.moods, {
    moodEerie: 'inquietante',
    moodMysterious: 'misterioso',
    moodRomantic: 'romántico',
    moodSerene: 'sereno y apacible',
    moodDramatic: 'dramático e intenso',
    moodJoyful: 'alegre y vibrante',
    moodNostalgic: 'nostálgico y cálido',
    moodElegant: 'elegante y sofisticado',
    moodEpic: 'épico y cinematográfico',
    moodDreamy: 'soñador y etéreo',
    moodDark: 'oscuro y melancólico',
    moodMagical: 'mágico y encantador',
    moodCozy: 'acogedor y cálido',
    moodTense: 'tenso y de suspense',
    moodHopeful: 'esperanzador y elevador',
    moodMelancholic: 'melancólico y reflexivo',
    moodPlayful: 'juguetón y divertido',
    moodWhimsical: 'caprichoso y peculiar',
    moodLux: 'lujoso y refinado',
    moodMinimal: 'minimalista y limpio',
    moodFuturistic: 'futurista y pulido',
    moodApocalyptic: 'apocalíptico y sombrío',
    moodEnergetic: 'enérgico e intenso',
    moodCalm: 'calmado y silencioso',
    moodMystic: 'místico y espiritual',
    moodBittersweet: 'agridulce, feliz y triste a la vez'
  });

  applyOrder(
    D.backgroundPresets.reduce((acc, g) => acc.concat(g.options), []),
    [
      'cementerio gótico abandonado de noche, lápidas antiguas cubiertas de musgo, árboles retorcidos, verja oxidada al fondo, cielo gris púrpura con luna llena entre nubes',
      'mansión victoriana oscura, vidrieras rotas, jardín muerto, porche de madera crujiente, murciélagos en cielo iluminado por la luna',
      'bosque encantado oscuro, árboles retorcidos, ojos brillando entre sombras, sendero de piedra cubierto de hojas secas, niebla espesa entre troncos',
      'interior de guarida de bruja, caldero verde burbujeando, frascos y calaveras en estantes, telarañas, velas parpadeantes, grimorios antiguos',
      'calle adoquinada con niebla a medianoche, farolas de gas titilantes, siluetas lejanas, ladrillo viejo, atmósfera victoriana',
      'interior de capilla de piedra abandonada, bancos rotos, luz azul lunar por vidrieras, polvo flotando, silencio inquietante',
      'pasillo polvoriento con telarañas, retratos agrietados, tablas crujientes, vela tenue',
      'lago maldito de noche, árboles muertos emergiendo del agua, brillo verdoso, niebla fina sobre la superficie',
      'jardín exuberante a la luz suave de la tarde, cerezos en flor con pétalos cayendo, sendero de piedra, colinas verdes y cielo pastel',
      'campo de tulipanes vibrante hasta el horizonte, filas rojas, amarillas y moradas, molino al fondo, cielo azul con nubes',
      'jardín de hadas con setas gigantes luminosas, luces diminutas, flores con rocío, musgo suave, destellos dorados',
      'pradera tranquila con flores altas, roble solitario con luz dorada, montañas lejanas, arroyo reflejando el cielo',
      'campo de lavanda al atardecer, filas moradas, luz dorada cálida, brisa suave, cielo pastel',
      'granja soleada con valla de madera, pacas de heno, granero pequeño, prados verdes, cielo azul con nubes',
      'bosque de pinos nevado al crepúsculo, lago helado reflejando cielo púrpura, cabaña acogedora con luz cálida, nieve suave, humo de chimenea',
      'villa navideña nocturna, tejados nevados, farolas cálidas, árbol en la plaza, trineo lejano, nieve cayendo',
      'castillo helado en la cima, auroras en el cielo, cristales de hielo flotando, cascada congelada, atmósfera azul y púrpura',
      'lago helado con hielo liso, ventisqueros, pinos lejanos, sol invernal pálido, cielo azul intenso',
      'playa turquesa al atardecer, agua cristalina con arrecife, arena blanca y palmeras, islas lejanas, cielo dorado con nubes rosas',
      'cascada tropical en piscina esmeralda, vegetación exuberante, flores exóticas, rayos de sol entre la copa, bruma en el agua',
      'isla tropical aislada con laguna turquesa, arena blanca, palmeras, hamaca de madera, sol y cielo despejado',
      'callejón cyberpunk con neón nocturno, vallas holográficas, calle mojada reflectante, rascacielos, vehículos voladores lejanos, vapor',
      'calle de Tokio lluviosa de noche, neón reflejado en el suelo, cruces con paraguas, humo de puestos de comida, ambiente urbano cinematográfico',
      'interior de estación espacial futurista, ventanal con la Tierra en órbita, pantallas holográficas, arquitectura blanca y azul, LED ambiental, partículas flotando',
      'azotea urbana moderna de noche, perfil de rascacielos, ventanas iluminadas, luz de helicóptero lejana, brisa suave',
      'gran biblioteca europea con estanterías altas, luz cálida, escaleras de madera, butacas de cuero, luz dorada por ventanales arqueados, polvo en el aire',
      'salón de palacio estilo Versalles, candelabros de cristal, paredes doradas con pinturas renacentistas, suelo de mármol, gran escalera',
      'ruinas de templo griego a la hora dorada, columnas de mármol con hiedra, mar Mediterráneo al fondo, sombras largas, flores silvestres entre piedras',
      'interior de teatro de ópera vintage, asientos de terciopelo rojo, ornamentación dorada, luces de escena dramáticas, atmósfera elegante',
      'sendero forestal cubierto de hojas rojas y doradas, arces y robles otoñales, puente de madera sobre arroyo, luz cálida filtrada',
      'cabaña rural acogedora con techo de paja, árboles otoñales, calabazas en el patio, muro de piedra con hiedra rojiza, humo de chimenea',
      'parque urbano en otoño, hojas doradas arremolinándose, bancos con luz cálida, atardecer suave, calma',
      'Un teléfono rojo de disco antiguo sonando solo en un campo de lavanda al atardecer, atmósfera misteriosa, hiperrealista, poca profundidad de campo',
      'Biblioteca abandonada donde los libros flotan y brillan con luz azul suave, partículas de polvo, realismo mágico, iluminación volumétrica',
      'Astronauta de juguete tirado en un arenero con un charco que refleja una nebulosa estrellada, mundo en miniatura, enfoque tilt-shift, onírico',
      'Decoración de cumpleaños infantil en una mansión gótica en ruinas, globos coloridos y telarañas, claroscuro dramático, alegría inquietante',
      'Callejón cyberpunk lluvioso con un único puesto de flores vintage brillando cálido, reflejos de neón en pétalos mojados, contraste cinematográfico',
      'Una cena romántica para dos servida dentro de un antiguo templo en ruinas, estrellas visibles a través del techo roto, enredaderas silvestres, íntimo',
      'Un club nocturno vacío y oscuro con un solo bebé llorando en una cuna en la pista de baile, la bola de discoteca aún girando, melancólico',
      'Una sala de hospital abandonada, un solo birrete de graduación y diploma sobre una camilla polvorienta, luz del sol por ventanas rotas, decadencia esperanzadora',
      'Una novia con vestido blanco de pie en un campo de batalla embarrado y humeante, sosteniendo un ramo de flores marchitas, cielo dramático',
      'Un viejo parque de atracciones de noche, un pequeño robot sentado en un carrusel, lágrimas de aceite cayendo, luces de neón parpadeando',
      'Un dormitorio oscuro iluminado solo por una pecera con medusas bioluminiscentes, brillo suave azul y rosa en las paredes, acogedor y surrealista',
      'Bosque de noche, los rayos de luna crean senderos brillantes en el suelo, las luciérnagas siguen los rastros de luz, mágico',
      'Callejón de mercado nocturno, toda la luz proviene de farolillos de papel rojo, todo lo demás en sombra azul profunda, misterioso y vibrante',
      'Una persona sosteniendo una linterna, el haz no ilumina el suelo sino pequeñas estrellas y constelaciones en el suelo, cósmico',
      'Estudio de fotografía profesional, paredes oscuras, iluminación de softbox y paraguas reflectantes, fondo de papel continuo en tono gris neutro, suelo mate, iluminación elegante y equilibrada',
      'Estudio de fotografía clásico, ciclorama blanco impecable, iluminación uniforme de alta clave (high-key), configuración minimalista y limpia, ideal para fotografía de catálogo o retratos corporativos',
      'Estudio fotográfico moderno, flashes de estudio con ventanas de luz, un taburete alto de madera en el centro frente a un fondo unicolor beige o terracota, ambiente cálido para retrato clásico',
      'Estudio fotográfico amplio y ordenado, paneles reflectores blancos y plateados (V-flats), iluminación rebotada suave y natural, fondo de papel texturizado, ambiente profesional y sobrio',
      'Estudio de moda profesional, fondo infinito blanco o gris claro, iluminación frontal tipo beauty dish (luz de belleza) para resaltar texturas, trípodes y equipos de fotografía visibles en los bordes, ambiente glamoroso y limpio',
      'Estudio fotográfico con rollos de fondos de papel en tonos pastel, iluminación continua suave, sombras suaves y definidas en la pared, estilo estandarizado para fotografía de catálogo (e-commerce)',
      'Mesa de fotografía de producto (bodegón), fondo blanco continuo en curva, caja de luz (lightbox) y reflectores pequeños, iluminación macro precisa para destacar detalles, estilo puramente comercial',
      'Estudio con telón de fondo de tela oscura o pintada a mano, un foco direccional creando iluminación dramática tipo Rembrandt, un asiento clásico de cuero, ambiente vintage, formal y elegante',
      'Parque urbano, árboles altos y verdes, pero un árbol tiene docenas de ojos en su tronco, observando, luz solar de la tarde, calma inquietante',
      'Jardín botánico, plantas exóticas, estatuas de mármol que parecen respirar (el pecho se mueve ligeramente), senderos de piedra, apacible pero vivo',
      'Bosque urbano, árboles densos, radios antiguas vintage colgando de las ramas emitiendo estática, luz natural filtrándose, nostálgico',
      'Jardín público, parterres de flores coloridas, cada flor emite un suave tono de campana cuando sopla el viento, primavera, realismo mágico',
      'Parque con un pequeño lago, un barco de papiroflexia gigante flotando, patos nadando a su alrededor, sauces, surrealista y apacible',
      'Jardín tropical exuberante, grandes palmeras, mariposas de vidrio de colores volando, la luz del sol creando sombras coloreadas',
      'Jardín zen japonés, patrones rastrillados en la arena que cambian solos, rocas cubiertas de musgo, valla de bambú, meditativo pero inquietante',
      'Campo de girasoles, un reloj de sol gigante de piedra en el centro, la sombra se mueve hacia atrás, luz cálida de verano, anomalía temporal',
      'Sala de estar moderna, sofá cómodo flotando unos centímetros sobre el suelo, mesa de centro con libros levitando, luz natural, calma surrealista',
      'Dormitorio, ventana grande, pero fuera hay un paisaje alienígena con dos soles, cama suave, iluminación cálida, ciencia ficción acogedora',
      'Cocina acogedora, armarios de madera, el frigorífico y la tostadora tienen caras monas y están charlando, iluminación cálida, caprichoso',
      'Oficina en casa, estantería, escritorio, retratos en la pared que te saludan con la mano, atmósfera cálida y productiva, mágico',
      'Baño elegante, superficies de mármol, el agua de la bañera brilla con luz dorada suave, plantas, tipo spa y místico',
      'Comedor familiar, mesa de madera, platos y cubiertos se colocan solos, iluminación cálida, vista a la ventana, hogar mágico',
      'Terraza, plantas en macetas que tararean melodías suaves, luces de cuerda, vista urbana, relajado y encantado',
      'Habitación acogedora con chimenea, llamas que danzan formando figuras de animales, iluminación cálida, muebles cómodos, íntimo y mágico',
      'Calle concurrida, cafeterías al aire libre, una máquina de escribir pública en una mesa pequeña con un cartel "escribe tu secreto", luz cálida de la tarde',
      'Calle comercial concurrida, escaparates, un maniquí cambia de pose cada pocos segundos, nadie lo nota, vida urbana dinámica',
      'Mercado local, puestos de productos frescos, un loro en una jaula que predice el futuro por una moneda, bullicioso, auténtico y mágico',
      'Andén de estación de tren, panel de salidas, un gran reloj que va hacia atrás, viajeros, detalles arquitectónicos, ambiente de viaje en el tiempo',
      'Andén de tren urbano al atardecer, una vieja maleta con pegatinas de ciudades ficticias, luz dorada suave, misterioso',
      'Calle con murales coloridos, los personajes pintados se mueven ligeramente, arte urbano en muros, creativo, vibrante y vivo',
      'Obra de construcción urbana, andamios, una grúa sosteniendo una enorme luna falsa de utilería, horizonte de la ciudad, surrealista industrial',
      'Plaza de la ciudad de noche, iluminación ambiental, pero cada farola proyecta una constelación distinta en el suelo, silencioso y cósmico',
      'Oficina corporativa, paredes de cristal, mobiliario moderno, pero peces coloridos nadan en el aire, luz natural brillante, lugar de trabajo surrealista',
      'Clínica médica, superficies limpias, equipamiento moderno, un esqueleto con bata de médico sosteniendo un portapapeles, estéril pero humorístico',
      'Sala de juntas, mesa grande, sillas, pantalla de presentación, pero un elefante invisible deja huellas en la alfombra, sátira empresarial',
      'Aula universitaria, pupitres, pizarra, tiza escribiendo fórmulas matemáticas sola, luz natural, magia académica',
      'Banco, suelos de mármol, escritorios profesionales, un viejo cofre del tesoro medio abierto con monedas de oro en medio del vestíbulo, formal pero pirata',
      'Terminal de aeropuerto, grandes ventanales, paneles de salidas que listan ciudades como la Atlántida y Narnia, viajeros, diseño moderno',
      'Pasillo de hospital moderno, paredes blancas limpias, plantas luminosas en macetas que emiten luz curativa, iluminación suave, esperanzador',
      'Sala de conciertos, escenario, butacas, un violín flotando y tocando un solo, iluminación dramática, paneles acústicos, artístico y mágico',
      'Fondo de dibujos animados colorido, dibujos de estrellas y formas que saltan del papel, juguetón, vibrante, sensación interactiva',
      'Tema de superhéroes, estilo cómic, una capa de tela real flotando al viento, colores vivos, iluminación dramática',
      'Tema de princesas, elementos de castillo, un espejo mágico que habla y hace muecas graciosas, rosa y púrpura brillante, cuento de hadas',
      'Tema de dinosaurios, jungla prehistórica, huellas de dinosaurio brillando en el suelo, aventurero, tonos verdes y marrones',
      'Tema de unicornios, arcoíris y brillillos, nubes de algodón de azúcar, colores pastel, mágico, caprichoso',
      'Castillo de cuento, torres y banderas, un dragón robot amistoso sentado en el muro, majestuoso pero de ciencia ficción',
      'Tema de circo, carpas y globos, animales de sombra actuando en la pared de la carpa, rojo y amarillo brillante, divertido y misterioso',
      'Espacio infantil, planetas y estrellas, un cohete de cartón con un niño astronauta, onírico, ciencia ficción colorida',
      'Fondo de animales tiernos, gatitos y cachorros esponjosos con gorros de chef diminutos y delantales, colores pastel suaves, cálido y divertido',
      'Tema de videojuegos, estilo pixel art, pero los píxeles se mueven y cambian de color, juego retro, nostálgico, divertido',
      'Fondo liso de color sólido, superficie uniforme pero con polvo de estrellas diminuto brillando, minimalista limpio, estudio mágico',
      'Fondo degradado, transición de color suave, niebla animada suave moviéndose lentamente, crea profundidad, moderno',
      'Fondo con formas de luz proyectadas, siluetas de animales en movimiento, diseño de iluminación creativo, estética caprichosa',
      'Fondo sólido con áreas de brillo controlado, halos suaves detrás del sujeto, estudio dimensional, angélico',
      'Fondo negro profundo continuo, superficie negra pura pero con estrellas tenues, estudio dramático, editorial cósmico',
      'Fondo blanco limpio continuo, superficie blanca pura, pero sombras de colores (rosa, azul), iluminación difusa suave, comercial creativo',
      'Fondo de textura de tela, cortinas elegantes que se mueven lentamente como si respiraran, estudio de retrato clásico, textura viva',
      'Fondo de colores vibrantes, colores saturados y audaces, destellos prismáticos y reflejos de arcoíris, estudio dinámico, moda'
    ]
  );
})();
